// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"student/internal/conf"
	"student/internal/pkg/nacos"
	"student/internal/rbac-service/biz"
	"student/internal/rbac-service/data"
	"student/internal/rbac-service/server"
	"student/internal/rbac-service/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger, discovery *nacos.Discovery) (*kratos.App, func(), error) {
	db := data.NewGormDB(bootstrap)
	client := data.NewRedis(bootstrap)
	string2 := data.NewRBACModelPath(bootstrap)
	enforcer := data.NewEnforcer(db, string2)
	dataData, cleanup, err := data.NewData(logger, db, client, enforcer)
	if err != nil {
		return nil, nil, err
	}
	rbacRepo := data.NewRBACRepo(dataData, logger)
	rbacUsecase := biz.NewRBACUsecase(rbacRepo, logger)
	rbacService := service.NewRBACService(rbacUsecase, logger)
	grpcServer := server.NewGRPCServer(bootstrap, rbacService, logger)
	httpServer := server.NewHTTPServer(bootstrap, rbacService, logger)
	app := newApp(logger, grpcServer, httpServer, discovery, bootstrap)
	return app, func() {
		cleanup()
	}, nil
}
