// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"student/internal/conf"
	"student/internal/gateway-service/server"
	"student/internal/pkg/nacos"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger, discovery *nacos.Discovery) (*kratos.App, func(), error) {
	httpServer := server.NewGatewayHTTPServer(bootstrap, discovery, logger)
	app := newApp(logger, httpServer, discovery, bootstrap)
	return app, func() {
	}, nil
}
