root = "."
tmp_dir = "bin"

[build]
  bin = "./bin/main"
  cmd = "go build -o ./bin/main ./cmd/..."
  delay = 1000
  exclude_dir = ["assets", "tmp", "bin", "vendor", "third_party", "helm", "database"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "APP_ENV=dev APP_USER=air ./bin/main -conf ./configs"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true
