// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: rbac/v1/rbac.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 角色相关消息
type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Role) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Role) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Role) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{1}
}

func (x *GetRoleRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleResponse) Reset() {
	*x = GetRoleResponse{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleResponse) ProtoMessage() {}

func (x *GetRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleResponse.ProtoReflect.Descriptor instead.
func (*GetRoleResponse) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{2}
}

func (x *GetRoleResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRoleRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoleResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRoleRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRoleRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleResponse) Reset() {
	*x = UpdateRoleResponse{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleResponse) ProtoMessage() {}

func (x *UpdateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoleResponse) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRoleResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRoleRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleResponse) Reset() {
	*x = DeleteRoleResponse{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleResponse) ProtoMessage() {}

func (x *DeleteRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRoleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{9}
}

func (x *ListRolesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRolesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRolesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*Role                `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{10}
}

func (x *ListRolesResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ListRolesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 权限相关消息
type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{11}
}

func (x *Permission) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Permission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Permission) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Permission) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Permission) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Permission) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Permission) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Permission) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionRequest) Reset() {
	*x = GetPermissionRequest{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionRequest) ProtoMessage() {}

func (x *GetPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionRequest.ProtoReflect.Descriptor instead.
func (*GetPermissionRequest) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{12}
}

func (x *GetPermissionRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *Permission            `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionResponse) Reset() {
	*x = GetPermissionResponse{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionResponse) ProtoMessage() {}

func (x *GetPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionResponse.ProtoReflect.Descriptor instead.
func (*GetPermissionResponse) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{13}
}

func (x *GetPermissionResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type CreatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionRequest) Reset() {
	*x = CreatePermissionRequest{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionRequest) ProtoMessage() {}

func (x *CreatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionRequest.ProtoReflect.Descriptor instead.
func (*CreatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{14}
}

func (x *CreatePermissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePermissionRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CreatePermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CreatePermissionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePermissionRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreatePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *Permission            `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionResponse) Reset() {
	*x = CreatePermissionResponse{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionResponse) ProtoMessage() {}

func (x *CreatePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionResponse.ProtoReflect.Descriptor instead.
func (*CreatePermissionResponse) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{15}
}

func (x *CreatePermissionResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type UpdatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionRequest) Reset() {
	*x = UpdatePermissionRequest{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionRequest) ProtoMessage() {}

func (x *UpdatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{16}
}

func (x *UpdatePermissionRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePermissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePermissionRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *UpdatePermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *UpdatePermissionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdatePermissionRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdatePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *Permission            `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionResponse) Reset() {
	*x = UpdatePermissionResponse{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionResponse) ProtoMessage() {}

func (x *UpdatePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionResponse.ProtoReflect.Descriptor instead.
func (*UpdatePermissionResponse) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{17}
}

func (x *UpdatePermissionResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type DeletePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionRequest) Reset() {
	*x = DeletePermissionRequest{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionRequest) ProtoMessage() {}

func (x *DeletePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionRequest.ProtoReflect.Descriptor instead.
func (*DeletePermissionRequest) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{18}
}

func (x *DeletePermissionRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeletePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionResponse) Reset() {
	*x = DeletePermissionResponse{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionResponse) ProtoMessage() {}

func (x *DeletePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionResponse.ProtoReflect.Descriptor instead.
func (*DeletePermissionResponse) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{19}
}

func (x *DeletePermissionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Resource      string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsRequest) Reset() {
	*x = ListPermissionsRequest{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsRequest) ProtoMessage() {}

func (x *ListPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{20}
}

func (x *ListPermissionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPermissionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPermissionsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListPermissionsRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type ListPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*Permission          `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsResponse) Reset() {
	*x = ListPermissionsResponse{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsResponse) ProtoMessage() {}

func (x *ListPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{21}
}

func (x *ListPermissionsResponse) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *ListPermissionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 用户角色相关消息
type UserRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        uint32                 `protobuf:"varint,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Role          *Role                  `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRole) Reset() {
	*x = UserRole{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRole) ProtoMessage() {}

func (x *UserRole) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRole.ProtoReflect.Descriptor instead.
func (*UserRole) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{22}
}

func (x *UserRole) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserRole) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserRole) GetRoleId() uint32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *UserRole) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserRole) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UserRole) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type GetUserRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesRequest) Reset() {
	*x = GetUserRolesRequest{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesRequest) ProtoMessage() {}

func (x *GetUserRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesRequest.ProtoReflect.Descriptor instead.
func (*GetUserRolesRequest) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{23}
}

func (x *GetUserRolesRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserRoles     []*UserRole            `protobuf:"bytes,1,rep,name=user_roles,json=userRoles,proto3" json:"user_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesResponse) Reset() {
	*x = GetUserRolesResponse{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesResponse) ProtoMessage() {}

func (x *GetUserRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesResponse.ProtoReflect.Descriptor instead.
func (*GetUserRolesResponse) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{24}
}

func (x *GetUserRolesResponse) GetUserRoles() []*UserRole {
	if x != nil {
		return x.UserRoles
	}
	return nil
}

type AssignUserRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        int32                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignUserRoleRequest) Reset() {
	*x = AssignUserRoleRequest{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignUserRoleRequest) ProtoMessage() {}

func (x *AssignUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignUserRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{25}
}

func (x *AssignUserRoleRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AssignUserRoleRequest) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type AssignUserRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignUserRoleResponse) Reset() {
	*x = AssignUserRoleResponse{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignUserRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignUserRoleResponse) ProtoMessage() {}

func (x *AssignUserRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignUserRoleResponse.ProtoReflect.Descriptor instead.
func (*AssignUserRoleResponse) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{26}
}

func (x *AssignUserRoleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveUserRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        int32                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserRoleRequest) Reset() {
	*x = RemoveUserRoleRequest{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserRoleRequest) ProtoMessage() {}

func (x *RemoveUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserRoleRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{27}
}

func (x *RemoveUserRoleRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveUserRoleRequest) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type RemoveUserRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserRoleResponse) Reset() {
	*x = RemoveUserRoleResponse{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserRoleResponse) ProtoMessage() {}

func (x *RemoveUserRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserRoleResponse.ProtoReflect.Descriptor instead.
func (*RemoveUserRoleResponse) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{28}
}

func (x *RemoveUserRoleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 角色权限相关消息
type RolePermission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleId        uint32                 `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionId  uint32                 `protobuf:"varint,3,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Permission    *Permission            `protobuf:"bytes,6,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePermission) Reset() {
	*x = RolePermission{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermission) ProtoMessage() {}

func (x *RolePermission) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermission.ProtoReflect.Descriptor instead.
func (*RolePermission) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{29}
}

func (x *RolePermission) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RolePermission) GetRoleId() uint32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RolePermission) GetPermissionId() uint32 {
	if x != nil {
		return x.PermissionId
	}
	return 0
}

func (x *RolePermission) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RolePermission) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *RolePermission) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type GetRolePermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int32                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePermissionsRequest) Reset() {
	*x = GetRolePermissionsRequest{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissionsRequest) ProtoMessage() {}

func (x *GetRolePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetRolePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{30}
}

func (x *GetRolePermissionsRequest) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type GetRolePermissionsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RolePermissions []*RolePermission      `protobuf:"bytes,1,rep,name=role_permissions,json=rolePermissions,proto3" json:"role_permissions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRolePermissionsResponse) Reset() {
	*x = GetRolePermissionsResponse{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissionsResponse) ProtoMessage() {}

func (x *GetRolePermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetRolePermissionsResponse) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{31}
}

func (x *GetRolePermissionsResponse) GetRolePermissions() []*RolePermission {
	if x != nil {
		return x.RolePermissions
	}
	return nil
}

type AssignRolePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int32                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionId  int32                  `protobuf:"varint,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRolePermissionRequest) Reset() {
	*x = AssignRolePermissionRequest{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRolePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRolePermissionRequest) ProtoMessage() {}

func (x *AssignRolePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRolePermissionRequest.ProtoReflect.Descriptor instead.
func (*AssignRolePermissionRequest) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{32}
}

func (x *AssignRolePermissionRequest) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *AssignRolePermissionRequest) GetPermissionId() int32 {
	if x != nil {
		return x.PermissionId
	}
	return 0
}

type AssignRolePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRolePermissionResponse) Reset() {
	*x = AssignRolePermissionResponse{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRolePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRolePermissionResponse) ProtoMessage() {}

func (x *AssignRolePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRolePermissionResponse.ProtoReflect.Descriptor instead.
func (*AssignRolePermissionResponse) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{33}
}

func (x *AssignRolePermissionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveRolePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int32                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionId  int32                  `protobuf:"varint,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRolePermissionRequest) Reset() {
	*x = RemoveRolePermissionRequest{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRolePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRolePermissionRequest) ProtoMessage() {}

func (x *RemoveRolePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRolePermissionRequest.ProtoReflect.Descriptor instead.
func (*RemoveRolePermissionRequest) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{34}
}

func (x *RemoveRolePermissionRequest) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RemoveRolePermissionRequest) GetPermissionId() int32 {
	if x != nil {
		return x.PermissionId
	}
	return 0
}

type RemoveRolePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRolePermissionResponse) Reset() {
	*x = RemoveRolePermissionResponse{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRolePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRolePermissionResponse) ProtoMessage() {}

func (x *RemoveRolePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRolePermissionResponse.ProtoReflect.Descriptor instead.
func (*RemoveRolePermissionResponse) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{35}
}

func (x *RemoveRolePermissionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 权限检查相关消息
type CheckPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionRequest) Reset() {
	*x = CheckPermissionRequest{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRequest) ProtoMessage() {}

func (x *CheckPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{36}
}

func (x *CheckPermissionRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *CheckPermissionRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CheckPermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type CheckPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasPermission bool                   `protobuf:"varint,1,opt,name=has_permission,json=hasPermission,proto3" json:"has_permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionResponse) Reset() {
	*x = CheckPermissionResponse{}
	mi := &file_rbac_v1_rbac_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionResponse) ProtoMessage() {}

func (x *CheckPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_v1_rbac_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionResponse) Descriptor() ([]byte, []int) {
	return file_rbac_v1_rbac_proto_rawDescGZIP(), []int{37}
}

func (x *CheckPermissionResponse) GetHasPermission() bool {
	if x != nil {
		return x.HasPermission
	}
	return false
}

var File_rbac_v1_rbac_proto protoreflect.FileDescriptor

const file_rbac_v1_rbac_proto_rawDesc = "" +
	"\n" +
	"\x12rbac/v1/rbac.proto\x12\vapi.rbac.v1\x1a\x1cgoogle/api/annotations.proto\"\xa2\x01\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\" \n" +
	"\x0eGetRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"8\n" +
	"\x0fGetRoleResponse\x12%\n" +
	"\x04role\x18\x01 \x01(\v2\x11.api.rbac.v1.RoleR\x04role\"a\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\";\n" +
	"\x12CreateRoleResponse\x12%\n" +
	"\x04role\x18\x01 \x01(\v2\x11.api.rbac.v1.RoleR\x04role\"q\n" +
	"\x11UpdateRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\";\n" +
	"\x12UpdateRoleResponse\x12%\n" +
	"\x04role\x18\x01 \x01(\v2\x11.api.rbac.v1.RoleR\x04role\"#\n" +
	"\x11DeleteRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\".\n" +
	"\x12DeleteRoleResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"W\n" +
	"\x10ListRolesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"R\n" +
	"\x11ListRolesResponse\x12'\n" +
	"\x05roles\x18\x01 \x03(\v2\x11.api.rbac.v1.RoleR\x05roles\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xdc\x01\n" +
	"\n" +
	"Permission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"&\n" +
	"\x14GetPermissionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"P\n" +
	"\x15GetPermissionResponse\x127\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x17.api.rbac.v1.PermissionR\n" +
	"permission\"\x9b\x01\n" +
	"\x17CreatePermissionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"S\n" +
	"\x18CreatePermissionResponse\x127\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x17.api.rbac.v1.PermissionR\n" +
	"permission\"\xab\x01\n" +
	"\x17UpdatePermissionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\"S\n" +
	"\x18UpdatePermissionResponse\x127\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x17.api.rbac.v1.PermissionR\n" +
	"permission\")\n" +
	"\x17DeletePermissionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"4\n" +
	"\x18DeletePermissionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"y\n" +
	"\x16ListPermissionsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\"j\n" +
	"\x17ListPermissionsResponse\x129\n" +
	"\vpermissions\x18\x01 \x03(\v2\x17.api.rbac.v1.PermissionR\vpermissions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xb1\x01\n" +
	"\bUserRole\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\rR\x06roleId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x12%\n" +
	"\x04role\x18\x06 \x01(\v2\x11.api.rbac.v1.RoleR\x04role\".\n" +
	"\x13GetUserRolesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"L\n" +
	"\x14GetUserRolesResponse\x124\n" +
	"\n" +
	"user_roles\x18\x01 \x03(\v2\x15.api.rbac.v1.UserRoleR\tuserRoles\"I\n" +
	"\x15AssignUserRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x05R\x06roleId\"2\n" +
	"\x16AssignUserRoleResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"I\n" +
	"\x15RemoveUserRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x05R\x06roleId\"2\n" +
	"\x16RemoveUserRoleResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xd5\x01\n" +
	"\x0eRolePermission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\rR\x06roleId\x12#\n" +
	"\rpermission_id\x18\x03 \x01(\rR\fpermissionId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x127\n" +
	"\n" +
	"permission\x18\x06 \x01(\v2\x17.api.rbac.v1.PermissionR\n" +
	"permission\"4\n" +
	"\x19GetRolePermissionsRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x05R\x06roleId\"d\n" +
	"\x1aGetRolePermissionsResponse\x12F\n" +
	"\x10role_permissions\x18\x01 \x03(\v2\x1b.api.rbac.v1.RolePermissionR\x0frolePermissions\"[\n" +
	"\x1bAssignRolePermissionRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x05R\x06roleId\x12#\n" +
	"\rpermission_id\x18\x02 \x01(\x05R\fpermissionId\"8\n" +
	"\x1cAssignRolePermissionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"[\n" +
	"\x1bRemoveRolePermissionRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x05R\x06roleId\x12#\n" +
	"\rpermission_id\x18\x02 \x01(\x05R\fpermissionId\"8\n" +
	"\x1cRemoveRolePermissionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"`\n" +
	"\x16CheckPermissionRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"@\n" +
	"\x17CheckPermissionResponse\x12%\n" +
	"\x0ehas_permission\x18\x01 \x01(\bR\rhasPermission2\xc0\x10\n" +
	"\vRBACService\x12\\\n" +
	"\aGetRole\x12\x1b.api.rbac.v1.GetRoleRequest\x1a\x1c.api.rbac.v1.GetRoleResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/roles/{id}\x12c\n" +
	"\n" +
	"CreateRole\x12\x1e.api.rbac.v1.CreateRoleRequest\x1a\x1f.api.rbac.v1.CreateRoleResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/roles\x12h\n" +
	"\n" +
	"UpdateRole\x12\x1e.api.rbac.v1.UpdateRoleRequest\x1a\x1f.api.rbac.v1.UpdateRoleResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/roles/{id}\x12e\n" +
	"\n" +
	"DeleteRole\x12\x1e.api.rbac.v1.DeleteRoleRequest\x1a\x1f.api.rbac.v1.DeleteRoleResponse\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/roles/{id}\x12]\n" +
	"\tListRoles\x12\x1d.api.rbac.v1.ListRolesRequest\x1a\x1e.api.rbac.v1.ListRolesResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/roles\x12t\n" +
	"\rGetPermission\x12!.api.rbac.v1.GetPermissionRequest\x1a\".api.rbac.v1.GetPermissionResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/permissions/{id}\x12{\n" +
	"\x10CreatePermission\x12$.api.rbac.v1.CreatePermissionRequest\x1a%.api.rbac.v1.CreatePermissionResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/permissions\x12\x80\x01\n" +
	"\x10UpdatePermission\x12$.api.rbac.v1.UpdatePermissionRequest\x1a%.api.rbac.v1.UpdatePermissionResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/v1/permissions/{id}\x12}\n" +
	"\x10DeletePermission\x12$.api.rbac.v1.DeletePermissionRequest\x1a%.api.rbac.v1.DeletePermissionResponse\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/v1/permissions/{id}\x12u\n" +
	"\x0fListPermissions\x12#.api.rbac.v1.ListPermissionsRequest\x1a$.api.rbac.v1.ListPermissionsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/permissions\x12v\n" +
	"\fGetUserRoles\x12 .api.rbac.v1.GetUserRolesRequest\x1a!.api.rbac.v1.GetUserRolesResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/users/{user_id}/roles\x12\x7f\n" +
	"\x0eAssignUserRole\x12\".api.rbac.v1.AssignUserRoleRequest\x1a#.api.rbac.v1.AssignUserRoleResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/users/{user_id}/roles\x12\x86\x01\n" +
	"\x0eRemoveUserRole\x12\".api.rbac.v1.RemoveUserRoleRequest\x1a#.api.rbac.v1.RemoveUserRoleResponse\"+\x82\xd3\xe4\x93\x02%*#/v1/users/{user_id}/roles/{role_id}\x12\x8e\x01\n" +
	"\x12GetRolePermissions\x12&.api.rbac.v1.GetRolePermissionsRequest\x1a'.api.rbac.v1.GetRolePermissionsResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/roles/{role_id}/permissions\x12\x97\x01\n" +
	"\x14AssignRolePermission\x12(.api.rbac.v1.AssignRolePermissionRequest\x1a).api.rbac.v1.AssignRolePermissionResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/roles/{role_id}/permissions\x12\xa4\x01\n" +
	"\x14RemoveRolePermission\x12(.api.rbac.v1.RemoveRolePermissionRequest\x1a).api.rbac.v1.RemoveRolePermissionResponse\"7\x82\xd3\xe4\x93\x021*//v1/roles/{role_id}/permissions/{permission_id}\x12~\n" +
	"\x0fCheckPermission\x12#.api.rbac.v1.CheckPermissionRequest\x1a$.api.rbac.v1.CheckPermissionResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/permissions/checkB\x18Z\x16student/api/rbac/v1;v1b\x06proto3"

var (
	file_rbac_v1_rbac_proto_rawDescOnce sync.Once
	file_rbac_v1_rbac_proto_rawDescData []byte
)

func file_rbac_v1_rbac_proto_rawDescGZIP() []byte {
	file_rbac_v1_rbac_proto_rawDescOnce.Do(func() {
		file_rbac_v1_rbac_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rbac_v1_rbac_proto_rawDesc), len(file_rbac_v1_rbac_proto_rawDesc)))
	})
	return file_rbac_v1_rbac_proto_rawDescData
}

var file_rbac_v1_rbac_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_rbac_v1_rbac_proto_goTypes = []any{
	(*Role)(nil),                         // 0: api.rbac.v1.Role
	(*GetRoleRequest)(nil),               // 1: api.rbac.v1.GetRoleRequest
	(*GetRoleResponse)(nil),              // 2: api.rbac.v1.GetRoleResponse
	(*CreateRoleRequest)(nil),            // 3: api.rbac.v1.CreateRoleRequest
	(*CreateRoleResponse)(nil),           // 4: api.rbac.v1.CreateRoleResponse
	(*UpdateRoleRequest)(nil),            // 5: api.rbac.v1.UpdateRoleRequest
	(*UpdateRoleResponse)(nil),           // 6: api.rbac.v1.UpdateRoleResponse
	(*DeleteRoleRequest)(nil),            // 7: api.rbac.v1.DeleteRoleRequest
	(*DeleteRoleResponse)(nil),           // 8: api.rbac.v1.DeleteRoleResponse
	(*ListRolesRequest)(nil),             // 9: api.rbac.v1.ListRolesRequest
	(*ListRolesResponse)(nil),            // 10: api.rbac.v1.ListRolesResponse
	(*Permission)(nil),                   // 11: api.rbac.v1.Permission
	(*GetPermissionRequest)(nil),         // 12: api.rbac.v1.GetPermissionRequest
	(*GetPermissionResponse)(nil),        // 13: api.rbac.v1.GetPermissionResponse
	(*CreatePermissionRequest)(nil),      // 14: api.rbac.v1.CreatePermissionRequest
	(*CreatePermissionResponse)(nil),     // 15: api.rbac.v1.CreatePermissionResponse
	(*UpdatePermissionRequest)(nil),      // 16: api.rbac.v1.UpdatePermissionRequest
	(*UpdatePermissionResponse)(nil),     // 17: api.rbac.v1.UpdatePermissionResponse
	(*DeletePermissionRequest)(nil),      // 18: api.rbac.v1.DeletePermissionRequest
	(*DeletePermissionResponse)(nil),     // 19: api.rbac.v1.DeletePermissionResponse
	(*ListPermissionsRequest)(nil),       // 20: api.rbac.v1.ListPermissionsRequest
	(*ListPermissionsResponse)(nil),      // 21: api.rbac.v1.ListPermissionsResponse
	(*UserRole)(nil),                     // 22: api.rbac.v1.UserRole
	(*GetUserRolesRequest)(nil),          // 23: api.rbac.v1.GetUserRolesRequest
	(*GetUserRolesResponse)(nil),         // 24: api.rbac.v1.GetUserRolesResponse
	(*AssignUserRoleRequest)(nil),        // 25: api.rbac.v1.AssignUserRoleRequest
	(*AssignUserRoleResponse)(nil),       // 26: api.rbac.v1.AssignUserRoleResponse
	(*RemoveUserRoleRequest)(nil),        // 27: api.rbac.v1.RemoveUserRoleRequest
	(*RemoveUserRoleResponse)(nil),       // 28: api.rbac.v1.RemoveUserRoleResponse
	(*RolePermission)(nil),               // 29: api.rbac.v1.RolePermission
	(*GetRolePermissionsRequest)(nil),    // 30: api.rbac.v1.GetRolePermissionsRequest
	(*GetRolePermissionsResponse)(nil),   // 31: api.rbac.v1.GetRolePermissionsResponse
	(*AssignRolePermissionRequest)(nil),  // 32: api.rbac.v1.AssignRolePermissionRequest
	(*AssignRolePermissionResponse)(nil), // 33: api.rbac.v1.AssignRolePermissionResponse
	(*RemoveRolePermissionRequest)(nil),  // 34: api.rbac.v1.RemoveRolePermissionRequest
	(*RemoveRolePermissionResponse)(nil), // 35: api.rbac.v1.RemoveRolePermissionResponse
	(*CheckPermissionRequest)(nil),       // 36: api.rbac.v1.CheckPermissionRequest
	(*CheckPermissionResponse)(nil),      // 37: api.rbac.v1.CheckPermissionResponse
}
var file_rbac_v1_rbac_proto_depIdxs = []int32{
	0,  // 0: api.rbac.v1.GetRoleResponse.role:type_name -> api.rbac.v1.Role
	0,  // 1: api.rbac.v1.CreateRoleResponse.role:type_name -> api.rbac.v1.Role
	0,  // 2: api.rbac.v1.UpdateRoleResponse.role:type_name -> api.rbac.v1.Role
	0,  // 3: api.rbac.v1.ListRolesResponse.roles:type_name -> api.rbac.v1.Role
	11, // 4: api.rbac.v1.GetPermissionResponse.permission:type_name -> api.rbac.v1.Permission
	11, // 5: api.rbac.v1.CreatePermissionResponse.permission:type_name -> api.rbac.v1.Permission
	11, // 6: api.rbac.v1.UpdatePermissionResponse.permission:type_name -> api.rbac.v1.Permission
	11, // 7: api.rbac.v1.ListPermissionsResponse.permissions:type_name -> api.rbac.v1.Permission
	0,  // 8: api.rbac.v1.UserRole.role:type_name -> api.rbac.v1.Role
	22, // 9: api.rbac.v1.GetUserRolesResponse.user_roles:type_name -> api.rbac.v1.UserRole
	11, // 10: api.rbac.v1.RolePermission.permission:type_name -> api.rbac.v1.Permission
	29, // 11: api.rbac.v1.GetRolePermissionsResponse.role_permissions:type_name -> api.rbac.v1.RolePermission
	1,  // 12: api.rbac.v1.RBACService.GetRole:input_type -> api.rbac.v1.GetRoleRequest
	3,  // 13: api.rbac.v1.RBACService.CreateRole:input_type -> api.rbac.v1.CreateRoleRequest
	5,  // 14: api.rbac.v1.RBACService.UpdateRole:input_type -> api.rbac.v1.UpdateRoleRequest
	7,  // 15: api.rbac.v1.RBACService.DeleteRole:input_type -> api.rbac.v1.DeleteRoleRequest
	9,  // 16: api.rbac.v1.RBACService.ListRoles:input_type -> api.rbac.v1.ListRolesRequest
	12, // 17: api.rbac.v1.RBACService.GetPermission:input_type -> api.rbac.v1.GetPermissionRequest
	14, // 18: api.rbac.v1.RBACService.CreatePermission:input_type -> api.rbac.v1.CreatePermissionRequest
	16, // 19: api.rbac.v1.RBACService.UpdatePermission:input_type -> api.rbac.v1.UpdatePermissionRequest
	18, // 20: api.rbac.v1.RBACService.DeletePermission:input_type -> api.rbac.v1.DeletePermissionRequest
	20, // 21: api.rbac.v1.RBACService.ListPermissions:input_type -> api.rbac.v1.ListPermissionsRequest
	23, // 22: api.rbac.v1.RBACService.GetUserRoles:input_type -> api.rbac.v1.GetUserRolesRequest
	25, // 23: api.rbac.v1.RBACService.AssignUserRole:input_type -> api.rbac.v1.AssignUserRoleRequest
	27, // 24: api.rbac.v1.RBACService.RemoveUserRole:input_type -> api.rbac.v1.RemoveUserRoleRequest
	30, // 25: api.rbac.v1.RBACService.GetRolePermissions:input_type -> api.rbac.v1.GetRolePermissionsRequest
	32, // 26: api.rbac.v1.RBACService.AssignRolePermission:input_type -> api.rbac.v1.AssignRolePermissionRequest
	34, // 27: api.rbac.v1.RBACService.RemoveRolePermission:input_type -> api.rbac.v1.RemoveRolePermissionRequest
	36, // 28: api.rbac.v1.RBACService.CheckPermission:input_type -> api.rbac.v1.CheckPermissionRequest
	2,  // 29: api.rbac.v1.RBACService.GetRole:output_type -> api.rbac.v1.GetRoleResponse
	4,  // 30: api.rbac.v1.RBACService.CreateRole:output_type -> api.rbac.v1.CreateRoleResponse
	6,  // 31: api.rbac.v1.RBACService.UpdateRole:output_type -> api.rbac.v1.UpdateRoleResponse
	8,  // 32: api.rbac.v1.RBACService.DeleteRole:output_type -> api.rbac.v1.DeleteRoleResponse
	10, // 33: api.rbac.v1.RBACService.ListRoles:output_type -> api.rbac.v1.ListRolesResponse
	13, // 34: api.rbac.v1.RBACService.GetPermission:output_type -> api.rbac.v1.GetPermissionResponse
	15, // 35: api.rbac.v1.RBACService.CreatePermission:output_type -> api.rbac.v1.CreatePermissionResponse
	17, // 36: api.rbac.v1.RBACService.UpdatePermission:output_type -> api.rbac.v1.UpdatePermissionResponse
	19, // 37: api.rbac.v1.RBACService.DeletePermission:output_type -> api.rbac.v1.DeletePermissionResponse
	21, // 38: api.rbac.v1.RBACService.ListPermissions:output_type -> api.rbac.v1.ListPermissionsResponse
	24, // 39: api.rbac.v1.RBACService.GetUserRoles:output_type -> api.rbac.v1.GetUserRolesResponse
	26, // 40: api.rbac.v1.RBACService.AssignUserRole:output_type -> api.rbac.v1.AssignUserRoleResponse
	28, // 41: api.rbac.v1.RBACService.RemoveUserRole:output_type -> api.rbac.v1.RemoveUserRoleResponse
	31, // 42: api.rbac.v1.RBACService.GetRolePermissions:output_type -> api.rbac.v1.GetRolePermissionsResponse
	33, // 43: api.rbac.v1.RBACService.AssignRolePermission:output_type -> api.rbac.v1.AssignRolePermissionResponse
	35, // 44: api.rbac.v1.RBACService.RemoveRolePermission:output_type -> api.rbac.v1.RemoveRolePermissionResponse
	37, // 45: api.rbac.v1.RBACService.CheckPermission:output_type -> api.rbac.v1.CheckPermissionResponse
	29, // [29:46] is the sub-list for method output_type
	12, // [12:29] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_rbac_v1_rbac_proto_init() }
func file_rbac_v1_rbac_proto_init() {
	if File_rbac_v1_rbac_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rbac_v1_rbac_proto_rawDesc), len(file_rbac_v1_rbac_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rbac_v1_rbac_proto_goTypes,
		DependencyIndexes: file_rbac_v1_rbac_proto_depIdxs,
		MessageInfos:      file_rbac_v1_rbac_proto_msgTypes,
	}.Build()
	File_rbac_v1_rbac_proto = out.File
	file_rbac_v1_rbac_proto_goTypes = nil
	file_rbac_v1_rbac_proto_depIdxs = nil
}
