// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: errors/v1/errors.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用错误码枚举
type CommonErrorCode int32

const (
	// 成功
	CommonErrorCode_SUCCESS CommonErrorCode = 0
	// 客户端错误 (4xx)
	CommonErrorCode_BAD_REQUEST          CommonErrorCode = 400
	CommonErrorCode_UNAUTHORIZED         CommonErrorCode = 401
	CommonErrorCode_FORBIDDEN            CommonErrorCode = 403
	CommonErrorCode_NOT_FOUND            CommonErrorCode = 404
	CommonErrorCode_METHOD_NOT_ALLOWED   CommonErrorCode = 405
	CommonErrorCode_CONFLICT             CommonErrorCode = 409
	CommonErrorCode_UNPROCESSABLE_ENTITY CommonErrorCode = 422
	CommonErrorCode_TOO_MANY_REQUESTS    CommonErrorCode = 429
	// 服务器错误 (5xx)
	CommonErrorCode_INTERNAL_SERVER_ERROR CommonErrorCode = 500
	CommonErrorCode_NOT_IMPLEMENTED       CommonErrorCode = 501
	CommonErrorCode_BAD_GATEWAY           CommonErrorCode = 502
	CommonErrorCode_SERVICE_UNAVAILABLE   CommonErrorCode = 503
	CommonErrorCode_GATEWAY_TIMEOUT       CommonErrorCode = 504
	// 业务错误 (1000+)
	CommonErrorCode_VALIDATION_FAILED        CommonErrorCode = 1000
	CommonErrorCode_RESOURCE_NOT_FOUND       CommonErrorCode = 1001
	CommonErrorCode_RESOURCE_ALREADY_EXISTS  CommonErrorCode = 1002
	CommonErrorCode_INVALID_CREDENTIALS      CommonErrorCode = 1003
	CommonErrorCode_ACCOUNT_LOCKED           CommonErrorCode = 1004
	CommonErrorCode_ACCOUNT_DISABLED         CommonErrorCode = 1005
	CommonErrorCode_INSUFFICIENT_PERMISSIONS CommonErrorCode = 1006
	CommonErrorCode_RATE_LIMIT_EXCEEDED      CommonErrorCode = 1007
	CommonErrorCode_DATABASE_ERROR           CommonErrorCode = 1008
	CommonErrorCode_EXTERNAL_SERVICE_ERROR   CommonErrorCode = 1009
)

// Enum value maps for CommonErrorCode.
var (
	CommonErrorCode_name = map[int32]string{
		0:    "SUCCESS",
		400:  "BAD_REQUEST",
		401:  "UNAUTHORIZED",
		403:  "FORBIDDEN",
		404:  "NOT_FOUND",
		405:  "METHOD_NOT_ALLOWED",
		409:  "CONFLICT",
		422:  "UNPROCESSABLE_ENTITY",
		429:  "TOO_MANY_REQUESTS",
		500:  "INTERNAL_SERVER_ERROR",
		501:  "NOT_IMPLEMENTED",
		502:  "BAD_GATEWAY",
		503:  "SERVICE_UNAVAILABLE",
		504:  "GATEWAY_TIMEOUT",
		1000: "VALIDATION_FAILED",
		1001: "RESOURCE_NOT_FOUND",
		1002: "RESOURCE_ALREADY_EXISTS",
		1003: "INVALID_CREDENTIALS",
		1004: "ACCOUNT_LOCKED",
		1005: "ACCOUNT_DISABLED",
		1006: "INSUFFICIENT_PERMISSIONS",
		1007: "RATE_LIMIT_EXCEEDED",
		1008: "DATABASE_ERROR",
		1009: "EXTERNAL_SERVICE_ERROR",
	}
	CommonErrorCode_value = map[string]int32{
		"SUCCESS":                  0,
		"BAD_REQUEST":              400,
		"UNAUTHORIZED":             401,
		"FORBIDDEN":                403,
		"NOT_FOUND":                404,
		"METHOD_NOT_ALLOWED":       405,
		"CONFLICT":                 409,
		"UNPROCESSABLE_ENTITY":     422,
		"TOO_MANY_REQUESTS":        429,
		"INTERNAL_SERVER_ERROR":    500,
		"NOT_IMPLEMENTED":          501,
		"BAD_GATEWAY":              502,
		"SERVICE_UNAVAILABLE":      503,
		"GATEWAY_TIMEOUT":          504,
		"VALIDATION_FAILED":        1000,
		"RESOURCE_NOT_FOUND":       1001,
		"RESOURCE_ALREADY_EXISTS":  1002,
		"INVALID_CREDENTIALS":      1003,
		"ACCOUNT_LOCKED":           1004,
		"ACCOUNT_DISABLED":         1005,
		"INSUFFICIENT_PERMISSIONS": 1006,
		"RATE_LIMIT_EXCEEDED":      1007,
		"DATABASE_ERROR":           1008,
		"EXTERNAL_SERVICE_ERROR":   1009,
	}
)

func (x CommonErrorCode) Enum() *CommonErrorCode {
	p := new(CommonErrorCode)
	*p = x
	return p
}

func (x CommonErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommonErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_v1_errors_proto_enumTypes[0].Descriptor()
}

func (CommonErrorCode) Type() protoreflect.EnumType {
	return &file_errors_v1_errors_proto_enumTypes[0]
}

func (x CommonErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommonErrorCode.Descriptor instead.
func (CommonErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_errors_v1_errors_proto_rawDescGZIP(), []int{0}
}

// 错误类型枚举
type ErrorType int32

const (
	ErrorType_UNKNOWN    ErrorType = 0
	ErrorType_STUDENT    ErrorType = 1
	ErrorType_USER       ErrorType = 2
	ErrorType_AUTH       ErrorType = 3
	ErrorType_VALIDATION ErrorType = 4
	ErrorType_DATABASE   ErrorType = 5
	ErrorType_EXTERNAL   ErrorType = 6
	ErrorType_SYSTEM     ErrorType = 7
)

// Enum value maps for ErrorType.
var (
	ErrorType_name = map[int32]string{
		0: "UNKNOWN",
		1: "STUDENT",
		2: "USER",
		3: "AUTH",
		4: "VALIDATION",
		5: "DATABASE",
		6: "EXTERNAL",
		7: "SYSTEM",
	}
	ErrorType_value = map[string]int32{
		"UNKNOWN":    0,
		"STUDENT":    1,
		"USER":       2,
		"AUTH":       3,
		"VALIDATION": 4,
		"DATABASE":   5,
		"EXTERNAL":   6,
		"SYSTEM":     7,
	}
)

func (x ErrorType) Enum() *ErrorType {
	p := new(ErrorType)
	*p = x
	return p
}

func (x ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_v1_errors_proto_enumTypes[1].Descriptor()
}

func (ErrorType) Type() protoreflect.EnumType {
	return &file_errors_v1_errors_proto_enumTypes[1]
}

func (x ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorType.Descriptor instead.
func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_errors_v1_errors_proto_rawDescGZIP(), []int{1}
}

// 获取错误信息请求
type GetErrorInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     int32                  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorType     string                 `protobuf:"bytes,2,opt,name=error_type,json=errorType,proto3" json:"error_type,omitempty"` // 可选：错误类型（如：student, user等）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetErrorInfoRequest) Reset() {
	*x = GetErrorInfoRequest{}
	mi := &file_errors_v1_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetErrorInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetErrorInfoRequest) ProtoMessage() {}

func (x *GetErrorInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_errors_v1_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetErrorInfoRequest.ProtoReflect.Descriptor instead.
func (*GetErrorInfoRequest) Descriptor() ([]byte, []int) {
	return file_errors_v1_errors_proto_rawDescGZIP(), []int{0}
}

func (x *GetErrorInfoRequest) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *GetErrorInfoRequest) GetErrorType() string {
	if x != nil {
		return x.ErrorType
	}
	return ""
}

// 获取错误信息响应
type GetErrorInfoReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode        int32                  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorType        string                 `protobuf:"bytes,2,opt,name=error_type,json=errorType,proto3" json:"error_type,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorDescription string                 `protobuf:"bytes,4,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty"`
	Solution         string                 `protobuf:"bytes,5,opt,name=solution,proto3" json:"solution,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetErrorInfoReply) Reset() {
	*x = GetErrorInfoReply{}
	mi := &file_errors_v1_errors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetErrorInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetErrorInfoReply) ProtoMessage() {}

func (x *GetErrorInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_errors_v1_errors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetErrorInfoReply.ProtoReflect.Descriptor instead.
func (*GetErrorInfoReply) Descriptor() ([]byte, []int) {
	return file_errors_v1_errors_proto_rawDescGZIP(), []int{1}
}

func (x *GetErrorInfoReply) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *GetErrorInfoReply) GetErrorType() string {
	if x != nil {
		return x.ErrorType
	}
	return ""
}

func (x *GetErrorInfoReply) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetErrorInfoReply) GetErrorDescription() string {
	if x != nil {
		return x.ErrorDescription
	}
	return ""
}

func (x *GetErrorInfoReply) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *GetErrorInfoReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetErrorInfoReply) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 获取错误码列表请求
type ListErrorCodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorType     string                 `protobuf:"bytes,1,opt,name=error_type,json=errorType,proto3" json:"error_type,omitempty"` // 可选：按错误类型过滤
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListErrorCodesRequest) Reset() {
	*x = ListErrorCodesRequest{}
	mi := &file_errors_v1_errors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListErrorCodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListErrorCodesRequest) ProtoMessage() {}

func (x *ListErrorCodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_errors_v1_errors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListErrorCodesRequest.ProtoReflect.Descriptor instead.
func (*ListErrorCodesRequest) Descriptor() ([]byte, []int) {
	return file_errors_v1_errors_proto_rawDescGZIP(), []int{2}
}

func (x *ListErrorCodesRequest) GetErrorType() string {
	if x != nil {
		return x.ErrorType
	}
	return ""
}

func (x *ListErrorCodesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListErrorCodesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取错误码列表响应
type ListErrorCodesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errors        []*ErrorInfo           `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListErrorCodesReply) Reset() {
	*x = ListErrorCodesReply{}
	mi := &file_errors_v1_errors_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListErrorCodesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListErrorCodesReply) ProtoMessage() {}

func (x *ListErrorCodesReply) ProtoReflect() protoreflect.Message {
	mi := &file_errors_v1_errors_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListErrorCodesReply.ProtoReflect.Descriptor instead.
func (*ListErrorCodesReply) Descriptor() ([]byte, []int) {
	return file_errors_v1_errors_proto_rawDescGZIP(), []int{3}
}

func (x *ListErrorCodesReply) GetErrors() []*ErrorInfo {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ListErrorCodesReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListErrorCodesReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListErrorCodesReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 错误信息
type ErrorInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode        int32                  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorType        string                 `protobuf:"bytes,2,opt,name=error_type,json=errorType,proto3" json:"error_type,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorDescription string                 `protobuf:"bytes,4,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty"`
	Solution         string                 `protobuf:"bytes,5,opt,name=solution,proto3" json:"solution,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_errors_v1_errors_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_errors_v1_errors_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_errors_v1_errors_proto_rawDescGZIP(), []int{4}
}

func (x *ErrorInfo) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ErrorInfo) GetErrorType() string {
	if x != nil {
		return x.ErrorType
	}
	return ""
}

func (x *ErrorInfo) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ErrorInfo) GetErrorDescription() string {
	if x != nil {
		return x.ErrorDescription
	}
	return ""
}

func (x *ErrorInfo) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *ErrorInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ErrorInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 创建自定义错误请求
type CreateCustomErrorRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode        int32                  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorType        string                 `protobuf:"bytes,2,opt,name=error_type,json=errorType,proto3" json:"error_type,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorDescription string                 `protobuf:"bytes,4,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty"`
	Solution         string                 `protobuf:"bytes,5,opt,name=solution,proto3" json:"solution,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateCustomErrorRequest) Reset() {
	*x = CreateCustomErrorRequest{}
	mi := &file_errors_v1_errors_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomErrorRequest) ProtoMessage() {}

func (x *CreateCustomErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_errors_v1_errors_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomErrorRequest.ProtoReflect.Descriptor instead.
func (*CreateCustomErrorRequest) Descriptor() ([]byte, []int) {
	return file_errors_v1_errors_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCustomErrorRequest) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *CreateCustomErrorRequest) GetErrorType() string {
	if x != nil {
		return x.ErrorType
	}
	return ""
}

func (x *CreateCustomErrorRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CreateCustomErrorRequest) GetErrorDescription() string {
	if x != nil {
		return x.ErrorDescription
	}
	return ""
}

func (x *CreateCustomErrorRequest) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

// 创建自定义错误响应
type CreateCustomErrorReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ErrorInfo     *ErrorInfo             `protobuf:"bytes,2,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomErrorReply) Reset() {
	*x = CreateCustomErrorReply{}
	mi := &file_errors_v1_errors_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomErrorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomErrorReply) ProtoMessage() {}

func (x *CreateCustomErrorReply) ProtoReflect() protoreflect.Message {
	mi := &file_errors_v1_errors_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomErrorReply.ProtoReflect.Descriptor instead.
func (*CreateCustomErrorReply) Descriptor() ([]byte, []int) {
	return file_errors_v1_errors_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCustomErrorReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateCustomErrorReply) GetErrorInfo() *ErrorInfo {
	if x != nil {
		return x.ErrorInfo
	}
	return nil
}

var File_errors_v1_errors_proto protoreflect.FileDescriptor

const file_errors_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x16errors/v1/errors.proto\x12\terrors.v1\x1a\x1cgoogle/api/annotations.proto\"S\n" +
	"\x13GetErrorInfoRequest\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\terrorCode\x12\x1d\n" +
	"\n" +
	"error_type\x18\x02 \x01(\tR\terrorType\"\xfd\x01\n" +
	"\x11GetErrorInfoReply\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\terrorCode\x12\x1d\n" +
	"\n" +
	"error_type\x18\x02 \x01(\tR\terrorType\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12+\n" +
	"\x11error_description\x18\x04 \x01(\tR\x10errorDescription\x12\x1a\n" +
	"\bsolution\x18\x05 \x01(\tR\bsolution\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"g\n" +
	"\x15ListErrorCodesRequest\x12\x1d\n" +
	"\n" +
	"error_type\x18\x01 \x01(\tR\terrorType\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x8a\x01\n" +
	"\x13ListErrorCodesReply\x12,\n" +
	"\x06errors\x18\x01 \x03(\v2\x14.errors.v1.ErrorInfoR\x06errors\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xf5\x01\n" +
	"\tErrorInfo\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\terrorCode\x12\x1d\n" +
	"\n" +
	"error_type\x18\x02 \x01(\tR\terrorType\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12+\n" +
	"\x11error_description\x18\x04 \x01(\tR\x10errorDescription\x12\x1a\n" +
	"\bsolution\x18\x05 \x01(\tR\bsolution\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"\xc6\x01\n" +
	"\x18CreateCustomErrorRequest\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\terrorCode\x12\x1d\n" +
	"\n" +
	"error_type\x18\x02 \x01(\tR\terrorType\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12+\n" +
	"\x11error_description\x18\x04 \x01(\tR\x10errorDescription\x12\x1a\n" +
	"\bsolution\x18\x05 \x01(\tR\bsolution\"g\n" +
	"\x16CreateCustomErrorReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x123\n" +
	"\n" +
	"error_info\x18\x02 \x01(\v2\x14.errors.v1.ErrorInfoR\terrorInfo*\xb2\x04\n" +
	"\x0fCommonErrorCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x10\n" +
	"\vBAD_REQUEST\x10\x90\x03\x12\x11\n" +
	"\fUNAUTHORIZED\x10\x91\x03\x12\x0e\n" +
	"\tFORBIDDEN\x10\x93\x03\x12\x0e\n" +
	"\tNOT_FOUND\x10\x94\x03\x12\x17\n" +
	"\x12METHOD_NOT_ALLOWED\x10\x95\x03\x12\r\n" +
	"\bCONFLICT\x10\x99\x03\x12\x19\n" +
	"\x14UNPROCESSABLE_ENTITY\x10\xa6\x03\x12\x16\n" +
	"\x11TOO_MANY_REQUESTS\x10\xad\x03\x12\x1a\n" +
	"\x15INTERNAL_SERVER_ERROR\x10\xf4\x03\x12\x14\n" +
	"\x0fNOT_IMPLEMENTED\x10\xf5\x03\x12\x10\n" +
	"\vBAD_GATEWAY\x10\xf6\x03\x12\x18\n" +
	"\x13SERVICE_UNAVAILABLE\x10\xf7\x03\x12\x14\n" +
	"\x0fGATEWAY_TIMEOUT\x10\xf8\x03\x12\x16\n" +
	"\x11VALIDATION_FAILED\x10\xe8\a\x12\x17\n" +
	"\x12RESOURCE_NOT_FOUND\x10\xe9\a\x12\x1c\n" +
	"\x17RESOURCE_ALREADY_EXISTS\x10\xea\a\x12\x18\n" +
	"\x13INVALID_CREDENTIALS\x10\xeb\a\x12\x13\n" +
	"\x0eACCOUNT_LOCKED\x10\xec\a\x12\x15\n" +
	"\x10ACCOUNT_DISABLED\x10\xed\a\x12\x1d\n" +
	"\x18INSUFFICIENT_PERMISSIONS\x10\xee\a\x12\x18\n" +
	"\x13RATE_LIMIT_EXCEEDED\x10\xef\a\x12\x13\n" +
	"\x0eDATABASE_ERROR\x10\xf0\a\x12\x1b\n" +
	"\x16EXTERNAL_SERVICE_ERROR\x10\xf1\a*q\n" +
	"\tErrorType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSTUDENT\x10\x01\x12\b\n" +
	"\x04USER\x10\x02\x12\b\n" +
	"\x04AUTH\x10\x03\x12\x0e\n" +
	"\n" +
	"VALIDATION\x10\x04\x12\f\n" +
	"\bDATABASE\x10\x05\x12\f\n" +
	"\bEXTERNAL\x10\x06\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\a2\xd7\x02\n" +
	"\fErrorService\x12j\n" +
	"\fGetErrorInfo\x12\x1e.errors.v1.GetErrorInfoRequest\x1a\x1c.errors.v1.GetErrorInfoReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/errors/{error_code}\x12c\n" +
	"\x0eListErrorCodes\x12 .errors.v1.ListErrorCodesRequest\x1a\x1e.errors.v1.ListErrorCodesReply\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/errors\x12v\n" +
	"\x11CreateCustomError\x12#.errors.v1.CreateCustomErrorRequest\x1a!.errors.v1.CreateCustomErrorReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/errors/customB\x1aZ\x18student/api/errors/v1;v1b\x06proto3"

var (
	file_errors_v1_errors_proto_rawDescOnce sync.Once
	file_errors_v1_errors_proto_rawDescData []byte
)

func file_errors_v1_errors_proto_rawDescGZIP() []byte {
	file_errors_v1_errors_proto_rawDescOnce.Do(func() {
		file_errors_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errors_v1_errors_proto_rawDesc), len(file_errors_v1_errors_proto_rawDesc)))
	})
	return file_errors_v1_errors_proto_rawDescData
}

var file_errors_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_errors_v1_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_errors_v1_errors_proto_goTypes = []any{
	(CommonErrorCode)(0),             // 0: errors.v1.CommonErrorCode
	(ErrorType)(0),                   // 1: errors.v1.ErrorType
	(*GetErrorInfoRequest)(nil),      // 2: errors.v1.GetErrorInfoRequest
	(*GetErrorInfoReply)(nil),        // 3: errors.v1.GetErrorInfoReply
	(*ListErrorCodesRequest)(nil),    // 4: errors.v1.ListErrorCodesRequest
	(*ListErrorCodesReply)(nil),      // 5: errors.v1.ListErrorCodesReply
	(*ErrorInfo)(nil),                // 6: errors.v1.ErrorInfo
	(*CreateCustomErrorRequest)(nil), // 7: errors.v1.CreateCustomErrorRequest
	(*CreateCustomErrorReply)(nil),   // 8: errors.v1.CreateCustomErrorReply
}
var file_errors_v1_errors_proto_depIdxs = []int32{
	6, // 0: errors.v1.ListErrorCodesReply.errors:type_name -> errors.v1.ErrorInfo
	6, // 1: errors.v1.CreateCustomErrorReply.error_info:type_name -> errors.v1.ErrorInfo
	2, // 2: errors.v1.ErrorService.GetErrorInfo:input_type -> errors.v1.GetErrorInfoRequest
	4, // 3: errors.v1.ErrorService.ListErrorCodes:input_type -> errors.v1.ListErrorCodesRequest
	7, // 4: errors.v1.ErrorService.CreateCustomError:input_type -> errors.v1.CreateCustomErrorRequest
	3, // 5: errors.v1.ErrorService.GetErrorInfo:output_type -> errors.v1.GetErrorInfoReply
	5, // 6: errors.v1.ErrorService.ListErrorCodes:output_type -> errors.v1.ListErrorCodesReply
	8, // 7: errors.v1.ErrorService.CreateCustomError:output_type -> errors.v1.CreateCustomErrorReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_errors_v1_errors_proto_init() }
func file_errors_v1_errors_proto_init() {
	if File_errors_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errors_v1_errors_proto_rawDesc), len(file_errors_v1_errors_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_errors_v1_errors_proto_goTypes,
		DependencyIndexes: file_errors_v1_errors_proto_depIdxs,
		EnumInfos:         file_errors_v1_errors_proto_enumTypes,
		MessageInfos:      file_errors_v1_errors_proto_msgTypes,
	}.Build()
	File_errors_v1_errors_proto = out.File
	file_errors_v1_errors_proto_goTypes = nil
	file_errors_v1_errors_proto_depIdxs = nil
}
