// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"student/internal/conf"
	"student/internal/pkg/nacos"
	"student/internal/student-service/biz"
	"student/internal/student-service/data"
	"student/internal/student-service/server"
	"student/internal/student-service/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger, discovery *nacos.Discovery) (*kratos.App, func(), error) {
	db := data.NewGormDB(bootstrap)
	client := data.NewRedis(bootstrap)
	dataData, cleanup, err := data.NewData(logger, db, client)
	if err != nil {
		return nil, nil, err
	}
	studentRepo := data.NewStudentRepo(dataData, logger)
	studentUsecase := biz.NewStudentUsecase(studentRepo, logger)
	studentService := service.NewStudentService(studentUsecase, logger)
	grpcServer := server.NewGRPCServer(bootstrap, studentService, logger)
	httpServer := server.NewHTTPServer(bootstrap, studentService, logger)
	app := newApp(logger, grpcServer, httpServer, discovery, bootstrap)
	return app, func() {
		cleanup()
	}, nil
}
