// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"student/internal/conf"
	"student/internal/pkg/nacos"
	"student/internal/user-service/biz"
	"student/internal/user-service/data"
	"student/internal/user-service/server"
	"student/internal/user-service/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger, discovery *nacos.Discovery) (*kratos.App, func(), error) {
	db := data.NewGormDB(bootstrap)
	client := data.NewRedis(bootstrap)
	dataData, cleanup, err := data.NewData(logger, db, client)
	if err != nil {
		return nil, nil, err
	}
	config := data.NewJWTConfig(bootstrap)
	jwtUtil := data.NewJWTUtil(config)
	userRepo := data.NewUserRepo(dataData, logger, jwtUtil)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	userService := service.NewUserService(userUsecase, logger, jwtUtil)
	grpcServer := server.NewGRPCServer(bootstrap, userService, logger)
	httpServer := server.NewHTTPServer(bootstrap, userService, logger)
	app := newApp(logger, grpcServer, httpServer, discovery, bootstrap)
	return app, func() {
		cleanup()
	}, nil
}
