// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: student/v1/student_error.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StudentErrorReason int32

const (
	StudentErrorReason_NOT_FOUNT       StudentErrorReason = 0
	StudentErrorReason_CONTENT_MISSING StudentErrorReason = 1
	StudentErrorReason_UNAUTHORIZED    StudentErrorReason = 2
	StudentErrorReason_FORBIDDEN       StudentErrorReason = 3
)

// Enum value maps for StudentErrorReason.
var (
	StudentErrorReason_name = map[int32]string{
		0: "NOT_FOUNT",
		1: "CONTENT_MISSING",
		2: "UNAUTHORIZED",
		3: "FORBIDDEN",
	}
	StudentErrorReason_value = map[string]int32{
		"NOT_FOUNT":       0,
		"CONTENT_MISSING": 1,
		"UNAUTHORIZED":    2,
		"FORBIDDEN":       3,
	}
)

func (x StudentErrorReason) Enum() *StudentErrorReason {
	p := new(StudentErrorReason)
	*p = x
	return p
}

func (x StudentErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StudentErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_student_v1_student_error_proto_enumTypes[0].Descriptor()
}

func (StudentErrorReason) Type() protoreflect.EnumType {
	return &file_student_v1_student_error_proto_enumTypes[0]
}

func (x StudentErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StudentErrorReason.Descriptor instead.
func (StudentErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_student_v1_student_error_proto_rawDescGZIP(), []int{0}
}

var File_student_v1_student_error_proto protoreflect.FileDescriptor

const file_student_v1_student_error_proto_rawDesc = "" +
	"\n" +
	"\x1estudent/v1/student_error.proto\x12\n" +
	"student.v1\x1a\x13errors/errors.proto*w\n" +
	"\x12StudentErrorReason\x12\x13\n" +
	"\tNOT_FOUNT\x10\x00\x1a\x04\xa8E\x94\x03\x12\x19\n" +
	"\x0fCONTENT_MISSING\x10\x01\x1a\x04\xa8E\x90\x03\x12\x16\n" +
	"\fUNAUTHORIZED\x10\x02\x1a\x04\xa8E\x91\x03\x12\x13\n" +
	"\tFORBIDDEN\x10\x03\x1a\x04\xa8E\x93\x03\x1a\x04\xa0E\xf4\x03B\x1bZ\x19student/api/student/v1;v1b\x06proto3"

var (
	file_student_v1_student_error_proto_rawDescOnce sync.Once
	file_student_v1_student_error_proto_rawDescData []byte
)

func file_student_v1_student_error_proto_rawDescGZIP() []byte {
	file_student_v1_student_error_proto_rawDescOnce.Do(func() {
		file_student_v1_student_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_student_v1_student_error_proto_rawDesc), len(file_student_v1_student_error_proto_rawDesc)))
	})
	return file_student_v1_student_error_proto_rawDescData
}

var file_student_v1_student_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_student_v1_student_error_proto_goTypes = []any{
	(StudentErrorReason)(0), // 0: student.v1.StudentErrorReason
}
var file_student_v1_student_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_student_v1_student_error_proto_init() }
func file_student_v1_student_error_proto_init() {
	if File_student_v1_student_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_student_v1_student_error_proto_rawDesc), len(file_student_v1_student_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_student_v1_student_error_proto_goTypes,
		DependencyIndexes: file_student_v1_student_error_proto_depIdxs,
		EnumInfos:         file_student_v1_student_error_proto_enumTypes,
	}.Build()
	File_student_v1_student_error_proto = out.File
	file_student_v1_student_error_proto_goTypes = nil
	file_student_v1_student_error_proto_depIdxs = nil
}
